import type { Metadata } from "next";
import { Sora, Space_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import SidePanel from "@/components/SidePanel";


const sora = Sora({ subsets: ["latin"], weight: ["400", "700"] });
const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-row w-full">
            <SidePanel />
            <div className="flex flex-col w-full h-screen items-center">
                <Header />
                {children}
            </div>
        </div>
    );
}
