import type { Metadata } from "next";
import { Sora, Space_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SidePanel from "@/components/SidePanel";


const sora = Sora({ subsets: ["latin"], weight: ["400", "700"] });
const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.className} flex flex-row`}
      >
        <SidePanel />
        <div className="flex flex-col w-full items-center">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
